### PR TITLE
Added volume control functionality

### PR DESCRIPTION
**Pull request by virajp4**
This PR fixes the issue #4 .
(It shows 2 commits because I mistakenly added yesterdays commit into the upstream.)
closes: #4

### CODE REVIEW

**Comment by NavySaw23** [comment]
Hello Viraj, after going through the code I found out that it doesn't fix the intended issue.

The goal is to amplify the sound once the user has exceeded 100% on the slider, but currently, the provided code works by mapping the existing volume slider in 200 parts (i.e. in increments of 0.5) and keeps the range at 0-100%. 
The intended feature would be to keep the increments to 1% and amplify the volume if the slider goes above 100%.

Hence the PR cannot be merged.

**Comment by virajp4** [comment]
understood, will fix that.

**Comment by virajp4** [comment]
@NavySaw23 fixed the code using web audio api

**Comment by NavySaw23** [comment]
Thank you for your contribution @virajp4

**Pull request merged**
